# Generated by Django 2.1.7 on 2019-05-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('correct_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('last_result', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_category', models.CharField(choices=[('BLOQUE1', '1'), ('BLOQUE2', '2'), ('BLOQUE3', '3'), ('BLOQUE4', '4'), ('BLOQUE5', '5'), ('EXAMEN', '6')], max_length=10)),
                ('test_name', models.TextField()),
                ('test_description', models.TextField()),
            ],
        ),
    ]
