# Generated by Django 2.1.11 on 2019-11-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_test',
        ),
        migrations.AddField(
            model_name='question',
            name='question_quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='quizz_app.Quiz'),
            preserve_default=False,
        ),
    ]
