# Generated by Django 2.1.7 on 2019-05-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_question',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='quizz_app.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_test', to='quizz_app.Test'),
            preserve_default=False,
        ),
    ]
