# Generated by Django 2.1.7 on 2019-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0002_auto_20190527_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.TextField(unique=True),
        ),
    ]
