# Generated by Django 2.1.7 on 2019-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0003_auto_20190527_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.TextField(blank=True),
        ),
    ]
