# Generated by Django 2.1.7 on 2019-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0005_auto_20190527_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_tries',
            field=models.IntegerField(default=0),
        ),
    ]
