# Generated by Django 2.1.7 on 2019-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0006_test_test_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_ok',
            field=models.IntegerField(default=0),
        ),
    ]
