# Generated by Django 2.1.7 on 2019-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0007_test_test_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='last_result',
        ),
        migrations.AddField(
            model_name='question',
            name='question_ok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_tries',
            field=models.IntegerField(default=0),
        ),
    ]
