# Generated by Django 2.1.7 on 2019-05-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0008_auto_20190528_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_tries',
            new_name='question_fails',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_tries',
            new_name='test_fails',
        ),
    ]
