# Generated by Django 2.1.7 on 2019-05-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz_app', '0009_auto_20190529_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fails', models.IntegerField(default=0)),
                ('question_ok', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_fails', models.IntegerField(default=0)),
                ('test_ok', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_fails',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_ok',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_fails',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_ok',
        ),
        migrations.AddField(
            model_name='testuser',
            name='test_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_test', to='quizz_app.Test'),
        ),
        migrations.AddField(
            model_name='testuser',
            name='test_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionuser',
            name='question_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_question', to='quizz_app.Question'),
        ),
        migrations.AddField(
            model_name='questionuser',
            name='question_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
