# Generated by Django 2.1.7 on 2019-05-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0010_auto_20190529_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_category',
            field=models.CharField(choices=[('ALL', 0), ('BLOQUE1', 1), ('BLOQUE2', 2), ('BLOQUE3', 3), ('BLOQUE4', 4), ('CONSTITUCION', 5), ('EXAMEN', 6)], max_length=10),
        ),
    ]
