# Generated by Django 2.1.7 on 2019-06-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0012_auto_20190531_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='test_randomizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_test', to='quizz_app.CategoryTest'),
        ),
    ]
