# Generated by Django 2.1.7 on 2019-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_app', '0013_auto_20190618_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_category',
            field=models.CharField(max_length=150),
        ),
    ]
